# Digital Quest - Static Site Configuration

# Netlify configuration file
# This file provides settings for deploying the Digital Quest game to Netlify

# Build settings
[build]
  publish = "."
  command = ""  # No build command needed for static site

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

# Cache control for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables
[build.environment]
  NODE_VERSION = "16.13.0"

# Functions (not used for this static site)
[functions]
  directory = "functions"

# Dev settings
[dev]
  command = "python -m http.server 8888"
  port = 8888
  targetPort = 8888
  publish = "."
  framework = "#custom"
